# Generated by Django 5.2.9 on 2026-01-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='l645',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='p720',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='st05',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='st10',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='st20',
            field=models.BooleanField(null=True),
        ),
    ]
